// Har topic ka metadata. Content khud content/<module>/<id>.html mein hai.
// why = "ye kyu seekh rahe hain", practice = manifest wale "ab tumhari baari" sawaal
// (naye topics mein practice fragment ke andar hi hai), covers = page mein kya-kya hai.
const modules = [
  {
    id: 'm0', track: 'maths', page: 'maths.html', color: 'module-green', short: 'Maths', number: '00',
    title: 'Maths — zero se deep learning tak', eyebrow: 'SHARED MODULE • ML AUR DL DONO KE LIYE',
    intro: 'Dono specializations mein jo bhi maths lagti hai, sab yahan ek jagah hai. Level 1 mein symbols aur graph se shuru karte hain, Level 2 mein data aur slope, aur Level 3 mein woh cheezein jo deep learning mein roz aati hain — broadcasting, matrix gradients, moving average, convolution. Jitna zaroori ho utna padho, baaki baad mein aa jana.',
    path: ['Level 1: symbols, graph, function', 'Level 2: data, vectors, slope, Python', 'Level 3: deep learning ki maths'],
    topics: [
      { id: 'z1', slug: 'maths-symbols', part: 'Level 1 · Pehla kadam', title: 'Symbols aur formula padhna', subtitle: 'Formula = ek chhota sentence',
        why: 'Course ke har video mein symbols aayenge. Ye page tumhari dictionary hai — isse formula “darawna” se “padhne layak” ban jaata hai.',
        practice: [['x = [3, 1, 4] ho to Σ xᵢ kitna hai?', '3 + 1 + 4 = <b>8</b>.'], ['x₂⁽⁵⁾ ka matlab kya hai?', '5th example (row) ka 2nd feature (column).'], ['f = w·x + b, jahan w = 4, x = 2, b = −3. f kitna?', '4 × 2 − 3 = <b>5</b>.']] },
      { id: 'z2', slug: 'maths-graphs', part: 'Level 1 · Pehla kadam', title: 'Graph, line aur slope', subtitle: 'Rishte ki tasveer padhna',
        why: 'Linear regression literally ek line fit karna hai, aur cost function ek katori jaisa graph hai. Graph padhna aaya to aadha Module 1 aa gaya.',
        practice: [['y = 3x + 2 mein x = 4 pe y? Slope aur intercept?', 'y = 14. Slope = 3, intercept = 2.'], ['Points (1, 2) aur (3, 8) ke beech line ka slope?', '(8 − 2) ÷ (3 − 1) = <b>3</b>.']] },
      { id: 'z3', slug: 'maths-functions', part: 'Level 1 · Pehla kadam', title: 'Function = input-output machine', subtitle: 'f(x) ka asli matlab',
        why: 'ML model ek function hi hai. Training = us function ke knobs (w, b) ghumana. Ye idea poore course ki reedh ki haddi hai.',
        practice: [['f(x) = x² − 1. f(3) kitna?', '9 − 1 = <b>8</b>.'], ['f(x) = 2x, g(x) = x + 5. g(f(4))?', 'Pehle f(4) = 8, phir g(8) = <b>13</b>.']] },
      { id: 'z4', slug: 'maths-powers-e-log', part: 'Level 1 · Pehla kadam', title: 'Power, e aur log', subtitle: 'Sigmoid aur log loss ki chaabi',
        why: 'Sigmoid (logistic regression), softmax (multiclass) aur log loss (classification cost) — teeno e aur log pe chalte hain. Shape samajh gaye to formulas apne aap samajh aayenge.',
        practice: [['10⁻² kitna hai?', '1 ÷ 100 = <b>0.01</b>.'], ['sigmoid(0) kitna aur kyu?', 'e⁰ = 1, to 1 ÷ (1 + 1) = <b>0.5</b>.'], ['Sahi answer ko 0.9 chance diya vs 0.2 — kisme −log zyada?', '0.2 wale mein (≈ 1.61 vs ≈ 0.11). Kam chance = zyada saza.']] },
      { id: 'z5', slug: 'maths-average-probability', part: 'Level 2 · Data aur badlaav', title: 'Average, phailaav aur probability', subtitle: 'μ, σ aur chance',
        why: 'Feature scaling μ aur σ use karta hai, anomaly detection bell curve use karta hai, aur har classifier probability deta hai.',
        practice: [['[2, 4, 6] ka mean aur variance?', 'Mean = 4. Doori −2, 0, 2 → square 4, 0, 4 → variance = 8/3 ≈ <b>2.67</b>, σ ≈ 1.63.'], ['Do dice dono pe 6 aane ka chance?', '1/6 × 1/6 = <b>1/36 ≈ 0.028</b>.']] },
      { id: 'z6', slug: 'maths-vectors-matrices', part: 'Level 2 · Data aur badlaav', title: 'Vectors, matrices aur dot product', subtitle: 'List, table aur bill ka hisaab',
        why: 'Data ek table (matrix) hai, ek example ek list (vector) hai, aur model ka hisaab dot product hai. Neural network ki har layer ek matrix multiply hai.',
        practice: [['[1, 2, 3] · [4, 0, −1] kitna?', '4 + 0 − 3 = <b>1</b>.'], ['(50, 3) × (3, 10) ka shape? Aur (50, 3) × (4, 10)?', 'Pehla (50, 10). Doosra error, kyunki 3 ≠ 4.']] },
      { id: 'z7', slug: 'maths-slope-derivative', part: 'Level 2 · Data aur badlaav', title: 'Slope, derivative aur chain rule', subtitle: 'Bina calculus ke calculus',
        why: 'Gradient descent derivative se chalta hai aur backpropagation chain rule se. Intuition itna hi chahiye: “thoda hilaaun to kitna badlega?”',
        practice: [['J(w) = (w − 5)². w = 2 pe slope? Kis taraf chalna chahiye?', 'Slope = 2(2 − 5) = −6 (negative) → w <b>badhao</b> (right chalo).'], ['A 1 badhne se B 2 badhta hai, B 1 badhne se C 4 badhta hai. A 1 badhne se C?', '2 × 4 = <b>8</b>.']] },
      { id: 'z8', slug: 'maths-python-numpy', part: 'Level 2 · Data aur badlaav', title: 'Python aur NumPy crash course', subtitle: 'Labs chalane ke liye kaafi coding',
        why: 'Course ke saare labs Python + NumPy (aur baad mein TensorFlow) mein hain. Ye page tumhe notebook kholke khud experiment karne layak banata hai.',
        practice: [['np.array([1, 2, 3]) * 2 ka output?', '<code>[2 4 6]</code> — poori list pe ek saath.'], ['Sigmoid ka Python function likho.', '<code>def sigmoid(z): return 1 / (1 + np.exp(-z))</code>']] },
      { id: 'z9', slug: 'maths-broadcasting-shapes', part: 'Level 3 · Deep learning ki maths', title: 'Broadcasting, shapes aur reshape', subtitle: 'NumPy ka woh jaadu jo bugs bhi laata hai',
        why: 'Deep learning ka poora code shapes ke khel pe chalta hai. Broadcasting samajh gaye to aadhe bugs tum code chalane se pehle hi pakad loge.',
        covers: ['(m,), (m,1) aur (1,m) shapes ka farak — rank-1 array wali galti', 'Broadcasting ke rules: matrix + row, matrix + column, matrix + number', 'axis=0 / axis=1 pe sum aur mean, keepdims', 'Image ko ek column vector banana — reshape/flatten', 'Transpose aur assert se shape check karna'] },
      { id: 'z10', slug: 'maths-computation-graph', part: 'Level 3 · Deep learning ki maths', title: 'Computation graph aur activation ke derivatives', subtitle: 'Backprop ko chhote-chhote kadmon mein todna',
        why: 'Deep Learning Course 1 ka backpropagation isi graph pe chalta hai. Aur sigmoid, tanh, ReLU ke slopes baar-baar aayenge.',
        covers: ['Computation graph: forward left se right, backward right se left', 'Har node pe local slope × peeche se aaya slope (chain rule)', 'Sigmoid ka derivative σ(1 − σ) numbers ke saath, max slope 0.25', 'tanh ka derivative 1 − tanh², ReLU ka 0 ya 1', 'Saturation: sigmoid/tanh ke kinaaron pe slope almost zero kyu'] },
      { id: 'z11', slug: 'maths-matrix-gradients', part: 'Level 3 · Deep learning ki maths', title: 'Matrix gradients aur dimensions ka hisaab', subtitle: 'Shape dekh ke formula khud nikaal lo',
        why: 'Vectorized backprop ke formulas (dW = dZ·Xᵀ/m jaise) yaad karne ki zaroorat nahi — shapes se khud ban jaate hain. Ye skill deep networks ko debug karne mein bahut kaam aati hai.',
        covers: ['Element-wise multiply (*) vs matrix multiply (@)', 'Kisi cheez ka gradient hamesha usi cheez ke shape ka hota hai', 'dZ = A − Y ka seedha matlab', 'Shapes jod ke dW = (1/m)·dZ·Xᵀ nikaalna', 'db = examples pe average (sum axis=1, keepdims)', 'Backward jaate waqt transpose kyu aata hai'] },
      { id: 'z12', slug: 'maths-norms-similarity', part: 'Level 3 · Deep learning ki maths', title: 'Norms, distance aur cosine similarity', subtitle: 'Vector kitna bada hai, do vectors kitne milte-julte hain',
        why: 'L2 regularization, gradient checking, face recognition aur word embeddings — chaaron jagah vectors ki lambai ya unki doori naapni padti hai.',
        covers: ['L2 norm (lambai), L1 norm, squared L2', 'Frobenius norm — matrix ki “lambai”', 'Do vectors ke beech Euclidean distance', 'Cosine similarity: angle se similarity, −1 se 1 tak, numbers ke saath', 'Vector ko unit length pe normalize karna', 'Ye sab DL mein kahan-kahan aata hai'] },
      { id: 'z13', slug: 'maths-moving-average', part: 'Level 3 · Deep learning ki maths', title: 'Exponentially weighted (moving) average', subtitle: 'Shor wale data ki smooth line',
        why: 'Momentum, RMSprop, Adam aur batch norm — chaaron ke andar yahi ek chhota sa formula hai. Ise samajh liya to optimizers darawne nahi lagenge.',
        covers: ['Normal average vs moving average — kyu chahiye', 'v = βv + (1 − β)θ, table mein step by step', 'β se kitne “din” ka average banta hai: ≈ 1/(1 − β)', 'Bias correction: shuru ke values kam kyu aate hain aur 1 − βᵗ se kaise theek hote hain', 'Kahan use hota hai: momentum, RMSprop, Adam, batch norm'] },
      { id: 'z14', slug: 'maths-probability-2', part: 'Level 3 · Deep learning ki maths', title: 'Probability level 2: conditional, likelihood, cross-entropy', subtitle: 'Language models aur softmax ki bhasha',
        why: 'Language model ek sentence ki probability nikaalta hai, beam search sabse likely sentence dhundhta hai, aur har classifier cross-entropy se train hota hai. Ye sab yahan ki probability pe tika hai.',
        covers: ['Conditional probability P(A | B) — rozmarra ke example se', 'Chain rule of probability: sentence ki probability = shabdon ki probabilities ka product', 'Likelihood aur maximum likelihood (sikka example)', 'Negative log-likelihood = cross-entropy loss', 'argmax, aur distribution se sampling (np.random.choice)', 'Chhoti probabilities ka product → logs ka sum (underflow se bachna)'] },
      { id: 'z15', slug: 'maths-randomness-scale', part: 'Level 3 · Deep learning ki maths', title: 'Randomness, variance aur scale', subtitle: 'Weights random kyu, aur kitne bade',
        why: 'Weight initialization, vanishing/exploding gradients aur hyperparameter search — teeno ka secret variance aur scale mein hai.',
        covers: ['np.random.randn: mean 0, variance 1', 'Random number ko c se multiply karo to variance c² guna', 'n random cheezon ka sum — variance n guna badhta hai, isliye 1/n se scale', 'Baar baar multiply: 1.1⁵⁰ vs 0.9⁵⁰ (explode vs vanish)', 'Log scale pe random sampling: α = 10ʳ', 'Random seed — result dobara same lana'] },
      { id: 'z16', slug: 'maths-convolution', part: 'Level 3 · Deep learning ki maths', title: 'Convolution: sliding dot product', subtitle: 'Ek chhoti khidki jo photo pe ghoomti hai',
        why: 'CNN course ka har topic isi ek operation pe khada hai. Yahan sirf maths — CNN course mein iska kaam dekhenge.',
        covers: ['1D convolution: ek chalti hui khidki, numbers ke saath', '2D: patch × filter element-wise, phir sum — worked example', 'Filter / kernel ka matlab', 'Output size ka formula ⌊(n + 2p − f)/s⌋ + 1, padding aur stride ke saath', '3D: channels (RGB) pe filter kaise chalta hai', 'Max pooling = sliding max'] },
    ],
  },
  {
    id: 'm1', track: 'ml', page: 'supervised.html', color: 'module-blue', short: 'ML · 1', number: '01',
    title: 'Supervised Machine Learning', eyebrow: 'ML COURSE 1 • ANSWER KEY KE SAATH PADHAI',
    intro: 'Computer ko solved examples dikha ke sikhana — jaise exam se pehle solved papers. Number predict karna (regression) aur category chunna (classification), cost function, gradient descent, overfitting aur regularization.',
    path: ['Examples do', 'Line/curve banao', 'Galti naapo', 'Galti ghatao', 'Naye case pe predict'],
    topics: [
      { id: 's1', slug: 'ml-kya-hai', part: 'Buniyaad', title: 'Machine learning asal mein hai kya?', subtitle: 'Rules likhne ki jagah examples se seekhna',
        why: 'Poore course ka naksha: supervised vs unsupervised, regression vs classification. Har naya topic in dabbon mein se kisi ek mein fit hoga.',
        practice: [['“Kal Sensex kitne points pe band hoga?” — kaunsa type?', 'Supervised → <b>regression</b> (answer ek number).'], ['“Photos ko bina labels ke milte-julte groups mein baanto” — kaunsa type?', '<b>Unsupervised</b> → clustering.']] },
      { id: 's2', slug: 'linear-regression', part: 'Number predict karna', title: 'Linear regression — seedhi line ka model', subtitle: 'Sabse pehla aur sabse simple ML model',
        why: 'Ye course ka “hello world” hai. Isme jo seekhoge — model, parameters, prediction — wahi neural networks tak har jagah repeat hoga.',
        practice: [['w = 0.05, b = 5, size = 1000 sq ft → predicted price?', '0.05 × 1000 + 5 = <b>55 lakh</b>.'], ['w negative ho to line kaisi dikhegi?', 'Neeche girti hui — size badhe to prediction ghate.']] },
      { id: 's3', slug: 'cost-function', part: 'Number predict karna', title: 'Cost function — line ko marks dena', subtitle: 'Line kitni galat hai, ek number mein',
        why: 'Training ka matlab hi “cost ghatana” hai. Har model ka apna cost hota hai — ye pehla aur sabse simple wala hai.',
        practice: [['Guesses [10, 20], asli [12, 20]. Cost J (1/2m wala)?', 'Galti −2, 0 → square 4, 0 → total 4 → 4 ÷ (2 × 2) = <b>1</b>.'], ['Cost bahut kam hai — iska kya matlab?', 'Line training data ke bahut kareeb hai. (Naye data pe bhi achhi hai ya nahi, woh alag check.)']] },
      { id: 's4', slug: 'gradient-descent', part: 'Number predict karna', title: 'Gradient descent — pahad se neeche utarna', subtitle: 'Computer best w, b kaise dhundhta hai',
        why: 'Ye ML ka engine hai. Linear regression, logistic regression, neural networks — sab isi (ya iske smart version Adam) se train hote hain.',
        practice: [['w = 5, slope = 4, α = 0.1 → naya w?', '5 − 0.1 × 4 = <b>4.6</b>.'], ['Cost har step badh rahi hai. Pehla shak kispe?', 'Learning rate α bahut bada — ya code mein sign ka bug.']] },
      { id: 's5', slug: 'multiple-features', part: 'Better clues', title: 'Multiple features aur vectorization', subtitle: 'Price sirf size se nahi banta',
        why: 'Asli problems mein hamesha kai features hote hain. Vectorization se hi bade data pe training practical banti hai.',
        practice: [['w = [2, 1], x = [3, 4], b = 1 → f?', '6 + 4 + 1 = <b>11</b>.'], ['x₃⁽²⁾ kya hai?', '2nd example ka 3rd feature.']] },
      { id: 's6', slug: 'feature-scaling', part: 'Better clues', title: 'Feature scaling aur training check', subtitle: 'Sab features ko same “unit” mein laao',
        why: 'Ye chhoti si trick training ko kai guna fast kar deti hai, aur learning curve dekhna har ML engineer ki roz ki aadat hai.',
        practice: [['Mean 50, σ 10. Value 70 ka z-score?', '(70 − 50) ÷ 10 = <b>2</b>.'], ['Naye data ko scale karte waqt kaunsa μ aur σ?', '<b>Training</b> data wala.']] },
      { id: 's7', slug: 'feature-engineering', part: 'Better clues', title: 'Feature engineering aur polynomial regression', subtitle: 'Naye clues banao, line ko curve banao',
        why: 'Achhe features aksar model badalne se zyada fayda dete hain. Aur yahin se overfitting ka khatra bhi shuru hota hai.',
        practice: [['Plot ki lambai 20, chaudai 30. Kaunsa naya feature?', 'Area = <b>600</b>.'], ['x = 10 pe x² aur x³?', '100 aur 1000 — isliye polynomial ke saath scaling zaroori.']] },
      { id: 's8', slug: 'logistic-regression', part: 'Category chunna', title: 'Logistic regression aur sigmoid', subtitle: 'Kisi bhi number ko 0–1 ke chance mein badalna',
        why: 'Classification ka pehla model. Neural network ka har sigmoid neuron literally ek chhota logistic regression hai.',
        practice: [['w = 1, b = −4, x = 4 → z aur chance?', 'z = 0 → chance <b>0.5</b>.'], ['Threshold 0.5 se kam kab rakhoge?', 'Jab asli positive miss karna bahut mehenga ho — jaise bimaari screening.']] },
      { id: 's9', slug: 'decision-boundary', part: 'Category chunna', title: 'Decision boundary', subtitle: '“Haan” aur “na” ki border',
        why: 'Classifier kya “soch” raha hai, ye dekhne ka sabse visual tareeka. Complex boundaries ki zaroorat hi neural networks ki taraf le jaati hai.',
        practice: [['Boundary x₁ + x₂ = 3 hai. Point (1, 1.5) kis side?', 'z = 1 + 1.5 − 3 = −0.5 &lt; 0 → <b>class 0</b>.'], ['Gol (circle) boundary ke liye kaunse features chahiye?', 'x₁² aur x₂².']] },
      { id: 's10', slug: 'logistic-cost', part: 'Category chunna', title: 'Logistic cost (log loss)', subtitle: 'Confident galti = bhaari saza',
        why: 'Classification ka standard cost. Softmax wala loss aur neural network training dono isi idea pe hain.',
        practice: [['y = 1. f = 0.99 aur f = 0.01 pe loss?', '≈ 0.01 aur ≈ 4.6.'], ['y = 0 ho to formula ka kaunsa hissa bachta hai?', '−log(1 − f).']] },
      { id: 's11', slug: 'overfitting', part: 'Naye data pe bhi chale', title: 'Underfitting aur overfitting', subtitle: 'Bahut simple vs bahut ratta',
        why: 'ML ka sabse bada practical sawaal: kya model naye data pe chalega? Module 2 ka bias/variance isi ka detail hai.',
        practice: [['Train error 1%, naye data pe 25%. Kya problem?', '<b>Overfit</b> (high variance).'], ['Train aur naye dono pe 30%, jabki insaan 2% galti karte hain?', '<b>Underfit</b> (high bias).']] },
      { id: 's12', slug: 'regularization', part: 'Naye data pe bhi chale', title: 'Regularization — weights pe lagaam', subtitle: 'Model ko “zyada smart” banne se rokna',
        why: 'Overfitting ka sabse common ilaaj. Neural networks mein bhi exactly yahi idea use hota hai.',
        practice: [['λ bahut bada kar diya to kya hoga?', 'Saare w ≈ 0 → flat line → <b>underfit</b>.'], ['Model overfit ho raha hai. λ badhao ya ghatao?', '<b>Badhao</b>.']] },
    ],
  },
  {
    id: 'm2', track: 'ml', page: 'advanced.html', color: 'module-purple', short: 'ML · 2', number: '02',
    title: 'Advanced Learning Algorithms', eyebrow: 'ML COURSE 2 • COMPLEX PATTERNS + ASLI ENGINEERING',
    intro: 'Logistic regression ki team = neural network. Phir TensorFlow, activations, softmax, backprop — aur asli ML engineering: train/CV/test, bias-variance, error analysis, precision-recall. Aakhir mein decision trees, random forest aur XGBoost.',
    path: ['Neurons ki team', 'Train (backprop)', 'Check (train/CV/test)', 'Diagnose (bias/variance)', 'Trees bhi try karo'],
    topics: [
      { id: 'a1', slug: 'neural-network-idea', part: 'Neural networks', title: 'Neural network ka idea', subtitle: 'Neuron = chhota logistic regression, network = unki team',
        why: 'Deep learning — jo aaj photos, awaaz, ChatGPT jaise systems ke peeche hai — isi building block se shuru hota hai.',
        practice: [['Hidden layer ko “hidden” kyu kehte hain?', 'Training data mein uski sahi values nahi hoti — network khud tay karta hai ki wahan kya seekhe.'], ['Ek sigmoid neuron Module 1 ka kaunsa model hai?', '<b>Logistic regression</b>.']] },
      { id: 'a2', slug: 'forward-propagation', part: 'Neural networks', title: 'Forward propagation', subtitle: 'Left se right chalte hue prediction',
        why: 'Network prediction kaise banata hai — ye samjhe bina debugging namumkin hai. Shapes ki galti yahin pakdi jaati hai.',
        practice: [['x = [1, 2], w = [2, −1], b = 0.5 → z?', '2 − 2 + 0.5 = <b>0.5</b>.'], ['400 input features, layer 1 mein 25 neurons. W ka shape?', '<b>(400, 25)</b>.']] },
      { id: 'a3', slug: 'tensorflow', part: 'Neural networks', title: 'TensorFlow mein network banana', subtitle: 'Banao → compile → fit',
        why: 'Idea se asli working model tak ka pul. Industry mein neural networks isi tarah ki libraries se bante hain.',
        practice: [['TensorFlow ke teen main steps?', 'Sequential se model banao → compile(loss, optimizer) → fit(X, y).'], ['epochs = 10 ka matlab?', 'Poore training data pe 10 chakkar.']] },
      { id: 'a4', slug: 'activation-functions', part: 'Neural networks', title: 'Activation functions', subtitle: 'Sigmoid, ReLU, linear — kab kaunsa',
        why: 'Activation ke bina neural network sirf ek seedhi line hai. Sahi choice training speed aur output dono decide karti hai.',
        practice: [['Ghar ka price (kabhi negative nahi) — output activation?', '<b>ReLU</b> (linear bhi chal jaata hai).'], ['ReLU(−2) aur ReLU(3)?', '0 aur 3.']] },
      { id: 'a5', slug: 'softmax-multiclass', part: 'Neural networks', title: 'Multiclass aur softmax', subtitle: '2 nahi, kai options mein se ek',
        why: 'Digit recognition, language models ka “agla shabd” — sab multiclass hai. Softmax unka standard output hai.',
        practice: [['Scores [0, 0] ka softmax?', '[0.5, 0.5] — dono barabar.'], ['Photo mein ek saath kai objects ho sakte hain — softmax ya sigmoids?', 'Har object ke liye alag <b>sigmoid</b> (multi-label).']] },
      { id: 'a6', slug: 'backprop-adam', part: 'Neural networks', title: 'Backpropagation aur Adam', subtitle: 'Galti ki zimmedari peeche ki taraf baantna',
        why: 'Neural network seekhta kaise hai — iska asli jawab. Loss na gire to kya check karna hai, woh bhi yahin se aata hai.',
        practice: [['Backprop kya nikaalta hai aur Adam kya karta hai?', 'Backprop = har weight ka slope. Adam = un slopes se weights update (smart step size ke saath).'], ['f = w · x aur x = 3. f pe w ka asar (slope)?', '<b>3</b>.']] },
      { id: 'a7', slug: 'train-cv-test', part: 'Model ko check karo', title: 'Training, CV aur test set', subtitle: 'Practice, mock test, board exam',
        why: 'Bina honest evaluation ke tumhe pata hi nahi chalega ki model achha hai. Har ML project ka pehla engineering kadam.',
        practice: [['λ ya polynomial degree chunne ke liye kaunsa set?', '<b>Cross-validation (dev)</b>.'], ['Final number kis set pe report karte hain?', '<b>Test</b> set pe, sirf ek baar.']] },
      { id: 'a8', slug: 'bias-variance', part: 'Model ko check karo', title: 'Bias aur variance', subtitle: 'Pehle bimaari pehchano, phir dawai',
        why: 'Ye diagnosis mahino ki galat mehnat bachata hai: data jama karein, bada model banayein, ya λ badlein?',
        practice: [['Baseline 5%, train 6%, CV 15%?', '<b>High variance</b> → zyada data, λ badhao, kam features.'], ['Baseline 5%, train 15%, CV 16%?', '<b>High bias</b> → bada model, zyada features, λ ghatao.']] },
      { id: 'a9', slug: 'ml-development-cycle', part: 'Model ko check karo', title: 'ML development cycle', subtitle: 'Error analysis, data, transfer learning, deployment, ethics',
        why: 'Asli ML engineer ka roz ka kaam: galtiyan dekhna, sahi data jodna, pre-trained models use karna, aur zimmedari se launch karna.',
        practice: [['Error analysis mein 60 galtiyan “dhundhli photos”, 5 “ulti photos”. Pehle kya?', '<b>Dhundhli photos</b> pe kaam — zyada fayda.'], ['Sirf 500 photos hain. Transfer learning ka kaunsa option?', 'Pre-trained layers freeze karo, sirf nayi output layer train karo.']] },
      { id: 'a10', slug: 'precision-recall', part: 'Model ko check karo', title: 'Precision, recall aur F1', subtitle: 'Jab accuracy dhokha de',
        why: 'Fraud, bimaari, defects — jahan positive cases rare hain wahan yahi metrics sach batate hain.',
        practice: [['TP = 8, FP = 2, FN = 8. Precision aur recall?', 'P = 8/10 = <b>80%</b>, R = 8/16 = <b>50%</b>.'], ['Threshold badhane se aam taur pe kya hota hai?', 'Precision upar, recall neeche.']] },
      { id: 'a11', slug: 'decision-trees', part: 'Decision trees', title: 'Decision tree, entropy aur information gain', subtitle: '“20 sawaal” wala game',
        why: 'Table jaise data (Excel) pe trees bahut powerful hain, aur chhote tree insaan padh bhi sakta hai.',
        practice: [['4 mein 4 aam ki entropy? 4 mein 2 aam ki?', '<b>0</b> aur <b>1</b>.'], ['Colour feature (laal/hara/peela) tree mein kaise daalein?', '<b>One-hot</b>: teen alag haan/na features.']] },
      { id: 'a12', slug: 'random-forest-xgboost', part: 'Decision trees', title: 'Random forest aur XGBoost', subtitle: 'Ek tree ki jagah trees ki panchayat',
        why: 'Industry mein table data ke liye XGBoost aksar pehli pasand hai. Aur ye tay karna ki trees chunein ya neural network — engineer ka faisla.',
        practice: [['Random forest mein trees ek doosre se alag kaise bante hain?', 'Sampling with replacement + har split pe random features ka subset.'], ['Photos ki classification — trees ya neural network?', '<b>Neural network</b>.']] },
    ],
  },
  {
    id: 'm3', track: 'ml', page: 'unsupervised.html', color: 'module-green', short: 'ML · 3', number: '03',
    title: 'Unsupervised Learning, Recommenders, RL', eyebrow: 'ML COURSE 3 • DHUNDHO, SUJHAO, KHUD SEEKHO',
    intro: 'Bina labels ke groups (K-means) aur ajeeb cases (anomaly detection) dhundhna, Netflix jaise recommendations banana, PCA se data ko chhota karna, aur reward se seekhne wala reinforcement learning.',
    path: ['Groups dhundho', 'Ajeeb pakdo', 'Recommend karo', 'PCA', 'Reward se seekho'],
    topics: [
      { id: 'u1', slug: 'unsupervised-clustering', part: 'Clustering', title: 'Unsupervised learning aur clustering', subtitle: 'Answer key nahi, phir bhi structure',
        why: 'Duniya ka zyadatar data bina labels ka hai. Usme se kuch kaam ka nikaalna — yahan se shuru hota hai.',
        practice: [['Customers ke groups banana, koi label nahi — supervised ya unsupervised?', '<b>Unsupervised</b>.'], ['Cluster ka naam (“premium customers”) kaun deta hai?', '<b>Insaan</b> — model sirf group number deta hai.']] },
      { id: 'u2', slug: 'k-means', part: 'Clustering', title: 'K-means algorithm', subtitle: 'Jhande gaado, team banao, jhanda khiskao',
        why: 'Sabse popular clustering algorithm. Simple, fast, aur samajhne mein aasan.',
        practice: [['Points 0, 1, 9, 10; centers 0 aur 1. Pehle round ke baad naye centers?', 'c₁ = {0} → 0, c₂ = {1, 9, 10} → 6.67. Agle round mein 1 ab 0 ke paas → c₁ = 0.5, c₂ = 9.5.'], ['K-means se pehle scaling kyu?', 'Bade unit wala feature doori pe hawi ho jaata hai.']] },
      { id: 'u3', slug: 'k-means-cost-choose-k', part: 'Clustering', title: 'K-means cost, initialization aur K chunna', subtitle: 'Kai baar try karo, best rakho',
        why: 'Algorithm chalana aasan hai; achha result lena aur sahi K chunna asli skill hai.',
        practice: [['K-means ka cost kisi round mein badh sakta hai?', '<b>Nahi</b>. Badhe to code mein bug.'], ['3 runs ke final J: 5, 2, 8. Kaunsa rakhoge?', 'J = <b>2</b> wala.']] },
      { id: 'u4', slug: 'anomaly-gaussian', part: 'Anomaly detection', title: 'Anomaly detection aur Gaussian', subtitle: 'Normal pehchano, ajeeb pakdo',
        why: 'Fraud, machine failure, hacking — jahan “kharab” examples bahut kam hain, wahan ye kaam aata hai.',
        practice: [['μ = 100, σ = 10. Value 130 kitne σ door hai?', '<b>3σ</b> — bahut rare.'], ['σ chhota ho to bell curve kaisi?', 'Patli aur unchi.']] },
      { id: 'u5', slug: 'anomaly-algorithm', part: 'Anomaly detection', title: 'Anomaly detection algorithm aur evaluation', subtitle: 'ε, features aur supervised se farak',
        why: 'Algorithm ke saath yeh jaanna ki kab anomaly detection use karna hai aur kab supervised — engineering judgement.',
        practice: [['p(x₁) = 0.2, p(x₂) = 0.05, ε = 0.02. Anomaly hai?', '0.2 × 0.05 = 0.01 &lt; 0.02 → <b>haan</b>.'], ['Hazaaron labelled spam examples hain. Anomaly detection ya supervised?', '<b>Supervised</b>.']] },
      { id: 'u6', slug: 'recommender-features', part: 'Recommender systems', title: 'Recommender: item features ke saath', subtitle: 'Har user ke liye chhota linear regression',
        why: 'YouTube, Netflix, Amazon ka dil. Sabse simple version se shuru karke idea pakdo.',
        practice: [['User w = [0, 4], b = 1. Movie x = [0.2, 0.9]. Predicted rating?', '0 + 3.6 + 1 = <b>4.6</b>.'], ['“?” wale khaane cost mein gine jaate hain?', '<b>Nahi</b>, sirf rated khaane.']] },
      { id: 'u7', slug: 'collaborative-filtering', part: 'Recommender systems', title: 'Collaborative filtering aur binary labels', subtitle: 'User taste aur item features dono seekho',
        why: 'Jab item ke features pata hi na hon — bas users ka behaviour ho — tab ye algorithm kaam aata hai.',
        practice: [['Collaborative filtering mein kya-kya seekha jaata hai?', 'User ke w, b <b>aur</b> item ke features x.'], ['Video 2 second mein skip kiya — label?', 'Aam taur pe <b>0</b> (engaged nahi).']] },
      { id: 'u8', slug: 'mean-normalization', part: 'Recommender systems', title: 'Mean normalization, TensorFlow aur related items', subtitle: 'Naye user ko average do',
        why: 'Practical recommenders ke chhote par zaroori details: naye users, custom training loop, aur “ye bhi pasand aayega”.',
        practice: [['Movie ke ratings 4, 2, 3. Mean normalization ke saath naye user ka prediction?', 'Average = <b>3</b>.'], ['Cold start kya hai?', 'Naye user/item ke paas data nahi, isliye achhi recommendation mushkil.']] },
      { id: 'u9', slug: 'content-based-filtering', part: 'Recommender systems', title: 'Content-based filtering aur deep learning', subtitle: 'Profile match, retrieval aur ranking',
        why: 'Modern recommenders isi tarah bante hain — do neural networks, retrieval + ranking, aur ethics ka dhyan.',
        practice: [['vᵘ · vᵐ bada ho to matlab?', 'User aur movie ka <b>achha match</b>.'], ['Retrieval aur ranking mein farak?', 'Retrieval = jaldi se kuch sau candidates. Ranking = unpe accurate model se sorting.']] },
      { id: 'u10', slug: 'pca', part: 'Dimensionality reduction', title: 'PCA — bahut features ko kam mein samet-na', subtitle: 'Data ki best “photo angle”',
        why: 'Bahut features wale data ko aankh se dekhne (visualize) ka sabse common tareeka.',
        practice: [['Aaj kal PCA ka main use?', '<b>Visualization</b> (2D/3D mein dekhna).'], ['PCA ko target y chahiye?', '<b>Nahi</b> — ye unsupervised hai.']] },
      { id: 'u11', slug: 'reinforcement-learning-basics', part: 'Reinforcement learning', title: 'Reinforcement learning basics', subtitle: 'State, action, reward, return, policy',
        why: 'Teesra bada paradigm: na labels, na sirf data — balki actions ke results se seekhna.',
        practice: [['Rewards 0, 0, 100, γ = 0.9. Return?', '0.9² × 100 = <b>81</b>.'], ['Policy kya hai?', 'Har state mein kaunsa action lena hai — rule-book.']] },
      { id: 'u12', slug: 'q-function-bellman', part: 'Reinforcement learning', title: 'Q-function aur Bellman equation', subtitle: 'Abhi ka inaam + aage ka best',
        why: 'Q-values mil gaye to best action chunna trivial hai. Bellman equation unhe nikaalne ka raasta hai.',
        practice: [['R(s) = 0, γ = 0.5, agli state ka max Q = 40. Q(s, a)?', '0 + 0.5 × 40 = <b>20</b>.'], ['Q pata ho to best action kaise chunna?', 'Woh action jiska Q <b>sabse zyada</b>.']] },
      { id: 'u13', slug: 'deep-q-network', part: 'Reinforcement learning', title: 'Continuous states aur Deep Q-Network', subtitle: 'Lunar lander, ε-greedy, soft update',
        why: 'Asli duniya ke RL ka tareeka — aur poore course ko jodne wala aakhri topic.',
        practice: [['ε = 0.1 ka matlab?', '10% baar random action (exploration).'], ['Soft update kyu?', 'Targets dheere badlein, training stable rahe.']] },
    ],
  },

  // ===================== DEEP LEARNING SPECIALIZATION =====================
  {
    id: 'd1', track: 'dl', page: 'dl-neural-networks.html', color: 'module-blue', short: 'DL · 1', number: '01',
    title: 'Neural Networks and Deep Learning', eyebrow: 'DL COURSE 1 • NEURAL NETWORK KHUD BANAO',
    intro: 'Ek neuron (logistic regression) se shuru karke poora deep network haath se banana — notation, computation graph, vectorization, activation functions, backprop, aur L layers tak ki dimensions.',
    path: ['Ek neuron', 'Computation graph', 'Vectorize karo', 'Ek hidden layer', 'L layers'],
    topics: [
      { id: 'n1', slug: 'dl-what-is-deep-learning', part: 'Shuruaat', title: 'Deep learning kya hai, aur ab hi kyu chal pada?', subtitle: 'Neural network ka pehla idea aur scale ki kahani',
        why: 'Poore specialization ka context: neural network kis kaam aata hai, kaunse data pe kaunsa network, aur pichhle kuch saalon mein ye achanak itna powerful kyu ho gaya.',
        covers: ['Neural network ka idea ek apne rozmarra ke example se (ReLU jaisi shape)', 'Supervised learning mein NN kahan: ads, photos, awaaz, translation, self-driving', 'Structured vs unstructured data', 'Standard NN, CNN aur RNN — kaunsa kis data ke liye', 'Scale ki kahani: data, compute aur algorithms (sigmoid → ReLU)', 'Idea → code → experiment ka chakra fast kyu hona chahiye'] },
      { id: 'n2', slug: 'dl-binary-classification', part: 'Ek neuron', title: 'Binary classification aur notation', subtitle: 'Photo ko numbers ki lambi list banana',
        why: 'Poore course ki notation yahin set hoti hai. X ka shape, m, nₓ — ye clear ho gaya to aage ke formulas padhna aasan ho jaayega.',
        covers: ['Billi hai ya nahi — binary classification', 'Photo ko pixels ki lambi list mein kholna (apne size ke saath, jaise 32×32×3)', 'nₓ, m, (x⁽ⁱ⁾, y⁽ⁱ⁾) notation', 'X ka shape (nₓ, m): examples columns mein', 'Y ka shape (1, m)', 'Ye convention kyu (vectorization mein aasani)'] },
      { id: 'n3', slug: 'dl-logistic-regression-neuron', part: 'Ek neuron', title: 'Logistic regression — ek neuron wala network', subtitle: 'ŷ = σ(wᵀx + b), loss aur cost',
        why: 'Ye sabse chhota neural network hai. Iski training samajh li to deep network bas isi ko baar-baar jodna hai.',
        covers: ['ŷ = σ(wᵀx + b) ka matlab', 'Sigmoid kyu (0 se 1 ka chance)', 'Loss function: ek example pe galti', 'Squared error yahan kyu nahi (non-convex)', 'Log loss ka intuition: y = 1 aur y = 0 dono case', 'Cost function: saare examples ka average', 'Ye loss kahan se aaya — maximum likelihood ka chhota sa idea'] },
      { id: 'n4', slug: 'dl-computation-graph', part: 'Ek neuron', title: 'Gradient descent aur computation graph', subtitle: 'Forward mein hisaab, backward mein slopes',
        why: 'Backpropagation ka poora idea yahan ek chhote graph pe dikh jaata hai. Deep network mein bhi bilkul yahi hota hai, bas graph bada hota hai.',
        covers: ['Gradient descent ka recap: w := w − α·dw', 'Derivative = slope, chhote numbers se check karna', 'Computation graph ka ek apna chhota worked example (jaise ek bill ka hisaab)', 'Backward pass: har variable ka derivative graph pe', 'Code notation: dvar ka matlab “dJ/dvar”'] },
      { id: 'n5', slug: 'dl-logistic-gradients', part: 'Ek neuron', title: 'Logistic regression ke gradients', subtitle: 'dz = a − y ka jaadu',
        why: 'Yahi formulas neural network ki aakhri layer mein har jagah aayenge. Aur yahin pata chalta hai ki for-loops kyu dushman hain.',
        covers: ['Ek example ke liye computation graph: z → a → L', 'da, dz = a − y, dw = x·dz, db = dz', 'm examples ke liye: gradients ka average', 'Ek iteration ka poora algorithm (loops ke saath)', 'Do for-loops ki problem — slow kyu'] },
      { id: 'n6', slug: 'dl-vectorization', part: 'Ek neuron', title: 'Vectorization aur broadcasting', subtitle: 'For-loop hatao, speed badhao',
        why: 'Deep learning bade data pe chalta hai. Vectorization ke bina ek training run ghanton ki jagah dinon mein chalegi.',
        covers: ['Loop vs np.dot — speed ka farak', 'Forward pass vectorized: Z = wᵀX + b, A = σ(Z)', 'Backward vectorized: dZ = A − Y, dw = X·dZᵀ/m, db', 'Bina kisi loop ke poori iteration (sirf iterations wala loop bachta hai)', 'Broadcasting kaise b ko har column mein jod deta hai', 'Rank-1 array (5,) wali galti aur uska ilaaj'] },
      { id: 'n7', slug: 'dl-shallow-network', part: 'Ek hidden layer', title: 'Shallow neural network: ek hidden layer', subtitle: 'Neurons ko stack karke matrix banana',
        why: 'Pehli baar asli “network” banega. Aur yahin se W[1], a[1] jaisi layer notation shuru hoti hai jo aage har jagah chalegi.',
        covers: ['2-layer network ka dhaancha: input, hidden, output', 'Layers ginne ka rule, a[0] = x', 'Ek hidden neuron ka hisaab: z, a', 'Neurons ke weights ko W[1] matrix mein stack karna', 'Kai examples ek saath: A[1] ki rows = neurons, columns = examples'] },
      { id: 'n8', slug: 'dl-activation-functions', part: 'Ek hidden layer', title: 'Activation functions aur unke derivatives', subtitle: 'Sigmoid, tanh, ReLU, Leaky ReLU',
        why: 'Activation galat chuna to network ya to seekhega hi nahi ya bahut dheere seekhega. Aur backprop ke liye inke slopes chahiye.',
        covers: ['Sigmoid vs tanh (tanh zero ke aas-paas centred)', 'ReLU aur Leaky ReLU', 'Kaunsa kab: hidden mein ReLU, binary output mein sigmoid', 'Non-linear activation kyu zaroori — linear layers mil ke ek hi line', 'Derivatives: σ′ = a(1 − a), tanh′ = 1 − a², ReLU′, Leaky ReLU′'] },
      { id: 'n9', slug: 'dl-shallow-backprop', part: 'Ek hidden layer', title: 'Shallow network ka backprop aur random initialization', subtitle: 'Weights zero se shuru kyu nahi',
        why: 'Pehla poora backprop khud likhoge. Aur ek bahut common galti — sab weights zero rakhna — kyu network ko bekaar kar deti hai, woh yahan samjhoge.',
        covers: ['2-layer network ke backprop equations: dZ[2], dW[2], db[2], dZ[1], dW[1], db[1]', 'dZ[1] = W[2]ᵀdZ[2] * g′(Z[1]) ka matlab', 'Gradient descent ka poora loop', 'Zero initialization se symmetry problem', 'Random init × 0.01 — chhota kyu (tanh/sigmoid saturate na ho)'] },
      { id: 'n10', slug: 'dl-deep-network', part: 'Deep network', title: 'Deep L-layer network aur dimensions', subtitle: 'Kitni bhi layers, ek hi formula',
        why: 'Ab network ko kitna bhi gehra kar sakte ho. Dimensions ka hisaab sahi rakha to bugs ka sabse bada source khatam.',
        covers: ['Notation: L, n[l], a[l], W[l], b[l]', 'Layer l ka forward prop: Z[l] = W[l]A[l−1] + b[l], A[l] = g(Z[l])', 'Layers pe for-loop theek hai', 'Shapes: W[l] (n[l], n[l−1]), b[l] (n[l], 1), Z/A (n[l], m)', 'dW, db hamesha W, b ke shape ke'] },
      { id: 'n11', slug: 'dl-why-deep-building-blocks', part: 'Deep network', title: 'Deep kyu? Building blocks, parameters aur hyperparameters', subtitle: 'Poora network ek saath jodna',
        why: 'Course 1 ka final picture: deep network har layer ke forward-backward blocks se kaise banta hai, aur kaunsi cheezein tumhe khud chunni padti hain.',
        covers: ['Deep representation: edges → parts → chehra; awaaz → sounds → shabd', 'Circuit theory wala intuition: gehra network kam neurons mein kaam karta hai', 'Forward aur backward blocks, cache ka role', 'Layer l ka backward: dZ, dW, db, dA[l−1]', 'Parameters (W, b) vs hyperparameters (α, iterations, L, n[l], activation)', 'Deep learning ek experiment wala process hai', 'Dimaag wali analogy — kitni sahi, kitni nahi'] },
    ],
  },
  {
    id: 'd2', track: 'dl', page: 'dl-improving-networks.html', color: 'module-purple', short: 'DL · 2', number: '02',
    title: 'Improving Deep Neural Networks', eyebrow: 'DL COURSE 2 • TUNING, REGULARIZATION, OPTIMIZATION',
    intro: 'Network ban gaya — ab usko achha banana. Bias/variance, L2 aur dropout, initialization, gradient checking, mini-batches, momentum-RMSprop-Adam, hyperparameter search, batch norm, softmax aur TensorFlow.',
    path: ['Diagnose', 'Regularize', 'Setup sahi karo', 'Tez optimize karo', 'Tune karo'],
    topics: [
      { id: 'i1', slug: 'dl-train-dev-test-bias-variance', part: 'Setup aur diagnosis', title: 'Train/dev/test aur bias-variance', subtitle: 'Big data ke zamane ke naye rules',
        why: 'Har sudhar se pehle pata hona chahiye ki problem kya hai. Ye page tumhe network ka doctor banata hai.',
        covers: ['Data kaise baantein: purana 60/20/20 vs bade data mein 98/1/1', 'Dev aur test same distribution se hone chahiye', 'Sirf dev set, test nahi — kab theek hai', 'Bias aur variance numbers se (Bayes error ke saath)', 'Basic recipe: high bias → bada network; high variance → data/regularization', 'Deep learning mein bias-variance trade-off kam kyu hai'] },
      { id: 'i2', slug: 'dl-l2-regularization', part: 'Regularization', title: 'L2 regularization', subtitle: 'Weights ko chhota rakhne ki saza',
        why: 'Overfitting ka sabse standard ilaaj. Dropout ya kuch bhi fancy try karne se pehle ye aata hai.',
        covers: ['Logistic regression mein L2 (aur L1 kya karta hai)', 'Neural network mein Frobenius norm', 'Backprop mein extra term aur “weight decay” naam kyu', 'Regularization overfitting kaise ghataata hai — do intuitions', 'Debug karte waqt cost mein regularization term bhi plot karna'] },
      { id: 'i3', slug: 'dl-dropout', part: 'Regularization', title: 'Dropout', subtitle: 'Har baar kuch neurons ko chhutti',
        why: 'Computer vision jaise kaamon mein overfitting rokne ka bahut popular tareeka.',
        covers: ['Idea: training mein random neurons band', 'Inverted dropout ka code: mask, keep_prob, a /= keep_prob', 'Test time pe dropout nahi', 'Kaam kyu karta hai: kisi ek feature pe bharosa nahi kar sakte', 'Har layer ka alag keep_prob', 'Cost J ab saaf define nahi — debug kaise karein'] },
      { id: 'i4', slug: 'dl-augmentation-early-stopping', part: 'Regularization', title: 'Data augmentation aur early stopping', subtitle: 'Muft ka data aur sahi waqt pe rukna',
        why: 'Do aur hathiyaar overfitting ke khilaaf — ek sasta aur asardaar, doosra aasan par ek chhupi kamzori ke saath.',
        covers: ['Augmentation: flip, crop, rotate, distortion', 'Early stopping: dev error ka graph dekh ke rukna', 'Early stopping ki kamzori: do kaam ek knob se (orthogonalization)', 'L2 vs early stopping kab'] },
      { id: 'i5', slug: 'dl-normalizing-inputs', part: 'Optimization setup', title: 'Inputs normalize karna', subtitle: 'Training ko gol katori do',
        why: 'Ek chhota sa preprocessing step jo training ko kai guna tez kar sakta hai.',
        covers: ['Mean ghataao, variance se divide karo', 'Test data pe bhi training wala μ aur σ²', 'Lambi katori vs gol katori — gradient descent pe asar', 'Kab zaroori hai, kab farak kam'] },
      { id: 'i6', slug: 'dl-vanishing-exploding-init', part: 'Optimization setup', title: 'Vanishing/exploding gradients aur weight initialization', subtitle: 'Gehre network ka sabse purana dushman',
        why: 'Jitna gehra network, utna ye problem. Sahi initialization se training shuru hi theek jagah se hoti hai.',
        covers: ['Gehri linear network ka example apne numbers se (1 se thoda bada vs thoda chhota, L baar multiply)', 'Gradients pe iska asar', 'Ek neuron ke inputs jitne zyada, weights utne chhote', 'Var(w) = 2/n (He, ReLU ke liye), 1/n (Xavier, tanh ke liye)', 'Code: np.random.randn(shape) * np.sqrt(2 / n_prev)'] },
      { id: 'i7', slug: 'dl-gradient-checking', part: 'Optimization setup', title: 'Gradient checking', subtitle: 'Apne backprop pe shak karo, aur check karo',
        why: 'Backprop mein chhota sa bug network ko chupchaap kharab train karta hai. Ye technique us bug ko pakadti hai.',
        covers: ['Numerical derivative: (f(θ + ε) − f(θ − ε)) / 2ε', 'Do-taraf wala one-taraf se accurate kyu', 'Saare parameters ko ek bade θ vector mein', 'Check formula aur thresholds (10⁻⁷, 10⁻⁵, 10⁻³)', 'Tips: sirf debug mein, components dekho, regularization jodo, dropout band, random init pe aur thodi training ke baad'] },
      { id: 'i8', slug: 'dl-mini-batch', part: 'Optimization algorithms', title: 'Mini-batch gradient descent', subtitle: 'Poore data ka intezaar mat karo',
        why: 'Bade dataset pe training ka default tareeka. Har aage wala optimizer mini-batches pe hi chalta hai.',
        covers: ['Batch vs mini-batch, notation X{t}', 'Epoch ka matlab', 'Cost ka graph shor wala kyu', 'Batch size = m (batch), = 1 (stochastic), beech wala', 'Size kaise chunein: 64 se 512, memory mein fit', 'Shuffle + partition'] },
      { id: 'i9', slug: 'dl-exponentially-weighted-averages', part: 'Optimization algorithms', title: 'Exponentially weighted averages', subtitle: 'Momentum aur Adam ki neev',
        why: 'Aage ke teen optimizers isi ek idea pe khade hain.',
        covers: ['Shor wale rozmarra ke data (jaise daily AQI ya sabzi ke daam) pe smooth line', 'v_t = βv_{t−1} + (1 − β)θ_t', 'β = 0.9, 0.98, 0.5 — kitne din ka average', 'Purane din ka wazan kaise ghat-ta hai', 'Code mein ek hi variable', 'Bias correction v_t / (1 − βᵗ)'] },
      { id: 'i10', slug: 'dl-momentum-rmsprop-adam', part: 'Optimization algorithms', title: 'Momentum, RMSprop aur Adam', subtitle: 'Seedha gaddhe ki taraf, bina zig-zag',
        why: 'Adam aaj deep learning ka default optimizer hai. Ye page batata hai ki woh andar kya kar raha hai.',
        covers: ['Momentum: gradients ka moving average, zig-zag kam', 'RMSprop: squared gradients se divide, oscillation dabao', 'Adam = momentum + RMSprop + bias correction', 'Hyperparameters: α (tune), β₁ = 0.9, β₂ = 0.999, ε = 10⁻⁸'] },
      { id: 'i11', slug: 'dl-learning-rate-decay-local-optima', part: 'Optimization algorithms', title: 'Learning rate decay aur local optima ka sach', subtitle: 'Kadam dheere-dheere chhote karo',
        why: 'Training ke end mein finesse, aur ek purana darr (local minimum) jo high dimensions mein utna bada nahi hai.',
        covers: ['Decay kyu: end mein chhote kadam', 'α = α₀ / (1 + decay_rate × epoch) worked', 'Exponential, 1/√epoch, staircase, manual decay', 'High dimensions mein local optima kam, saddle points zyada', 'Plateaus: training slow kyu hoti hai'] },
      { id: 'i12', slug: 'dl-hyperparameter-tuning', part: 'Hyperparameter tuning', title: 'Hyperparameter tuning ka tareeka', subtitle: 'Grid nahi, random. Aur sahi scale pe.',
        why: 'Achha network aur average network mein aksar sirf sahi hyperparameters ka farak hota hai.',
        covers: ['Kaunsa hyperparameter kitna important (α sabse upar)', 'Grid search ki jagah random search kyu', 'Coarse to fine', 'Sahi scale: α ke liye log scale (r random, α = 10ʳ), β ke liye 1 − β', 'Compute kam ho to ek model ko dhyan se palna vs zyada ho to kai models ek saath (apni analogy)', 'Kuch mahino mein dobara check'] },
      { id: 'i13', slug: 'dl-batch-normalization', part: 'Hyperparameter tuning', title: 'Batch normalization', subtitle: 'Har layer ke andar bhi normalize karo',
        why: 'Batch norm se gehre networks tez aur stable train hote hain, aur hyperparameters ka chunaav kam nazuk ho jaata hai.',
        covers: ['Hidden layer ke Z ko normalize karna', 'γ aur β — network khud mean aur variance chune', 'Network mein kaise fit hota hai (mini-batch pe), b bekaar kyu', 'Kaam kyu karta hai: covariate shift, baad ki layers stable, thoda regularization', 'Test time pe: training ke μ, σ² ka moving average'] },
      { id: 'i14', slug: 'dl-softmax-regression', part: 'Multiclass', title: 'Softmax regression', subtitle: 'C classes mein se ek',
        why: 'Binary se aage — digits, animals, kuch bhi. Deep learning ka standard multiclass output.',
        covers: ['C classes aur output layer mein C units', 'Softmax: t = eᶻ, phir normalize — worked', 'Bina hidden layer ke softmax ki linear boundaries', 'Hardmax vs softmax', 'Loss: −Σ y log ŷ aur cost', 'Gradient dZ = Ŷ − Y', 'C = 2 pe logistic regression hi hai'] },
      { id: 'i15', slug: 'dl-frameworks-tensorflow', part: 'Multiclass', title: 'Deep learning frameworks aur TensorFlow', subtitle: 'Backprop library ko karne do',
        why: 'Ab tak sab haath se kiya. Asli projects mein framework chahiye — aur uske andar kya ho raha hai, woh tum ab jaante ho.',
        covers: ['Framework kaise chunein: aasani, speed, sach mein open', 'tf.Variable, GradientTape, optimizer', 'Ek chhota example: (w − 5)² ko minimize karna', 'Framework forward se backward khud bana leta hai (computation graph)', 'Custom training loop vs model.fit'] },
    ],
  },
  {
    id: 'd3', track: 'dl', page: 'dl-structuring-projects.html', color: 'module-green', short: 'DL · 3', number: '03',
    title: 'Structuring Machine Learning Projects', eyebrow: 'DL COURSE 3 • PROJECT KAISE CHALAYEIN',
    intro: 'Code nahi, soch. Kaunsa idea pehle try karein, metric kaise chunein, human-level se tulna, error analysis, alag distribution ka data, transfer aur multi-task learning, aur end-to-end kab.',
    path: ['Ek metric', 'Sahi dev/test', 'Human se tulna', 'Galtiyan dekho', 'Sahi strategy'],
    topics: [
      { id: 'p1', slug: 'dl-ml-strategy-orthogonalization', part: 'Setup', title: 'ML strategy aur orthogonalization', subtitle: 'Har problem ka apna alag knob',
        why: 'Ek project mein das idea hote hain aur time ek ka. Ye soch batati hai ki kaunsa knob ghumana hai.',
        covers: ['Strategy kyu: galat idea pe mahine barbaad', 'Orthogonalization: TV/gaadi ke controls wali analogy', 'Chaar kadmon ki chain: train → dev → test → real world, har ek ka apna knob', 'Early stopping “orthogonal” kyu nahi'] },
      { id: 'p2', slug: 'dl-single-number-metric', part: 'Setup', title: 'Ek number wala metric, satisficing aur optimizing', subtitle: 'Faisla jaldi lena hai to ek score chahiye',
        why: 'Do models mein se kaunsa behtar hai — ek number ho to ye sawaal seconds mein solve hota hai.',
        covers: ['Precision aur recall se F1', 'Kai regions/desh ke errors ka average', 'Satisficing (bas itna hona chahiye) vs optimizing (jitna ho sake)', 'N metrics: 1 optimizing, N − 1 satisficing', 'Apna example: product jahan accuracy ke saath speed/false alarms ki shart ho'] },
      { id: 'p3', slug: 'dl-dev-test-setup', part: 'Setup', title: 'Dev/test set lagana, aur kab badalna', subtitle: 'Nishaana sahi jagah lagao',
        why: 'Dev set aur metric team ka nishaana hain. Nishaana galat jagah laga to poori team galat disha mein daudti hai.',
        covers: ['Dev aur test same distribution se, future data jaise', 'Galat split ka apna example', 'Dev/test ka size aaj ke zamane mein', 'Metric kab badalna: apna example, weighted error', 'Pehle nishaana tay karo, phir nishaana lagana — alag kaam', 'Dev set user data jaisa na ho to dev set badlo'] },
      { id: 'p4', slug: 'dl-human-level-performance', part: 'Human se tulna', title: 'Human-level performance aur avoidable bias', subtitle: 'Insaan kitna achha hai, is se pata chalta hai kya karna hai',
        why: 'Train error 8% achha hai ya bura? Jawab is baat pe tika hai ki insaan kitni galti karte hain.',
        covers: ['Insaan se tulna kyu, aur Bayes error', 'Human-level ke paas progress slow kyu hoti hai', 'Avoidable bias vs variance — numbers ke saath do scenarios', 'Human-level kise maanein (aam insaan, expert, experts ki team) — apne domain ke example se', 'Human-level se aage nikalna — kaunse kaamon mein aasan', 'Model sudhaarne ki poori checklist'] },
      { id: 'p5', slug: 'dl-error-analysis', part: 'Galtiyon se seekhna', title: 'Error analysis aur galat labels', subtitle: '100 galtiyan dekho, mahine bachao',
        why: 'Sabse bada ROI wala kaam: galtiyon ko khud dekhna aur tay karna ki kahan mehnat karni hai.',
        covers: ['100 galat dev examples dekhna, ceiling ka hisaab', 'Kai ideas ek spreadsheet mein parallel check', 'Galat labels: random errors se DL nahi darta, systematic se darta hai', 'Labels theek karne layak kab (numbers ke saath)', 'Dev aur test dono pe same process, sahi examples bhi dekho', 'Pehla system jaldi banao, phir iterate'] },
      { id: 'p6', slug: 'dl-mismatched-distributions', part: 'Alag distribution ka data', title: 'Training aur testing alag distributions pe', subtitle: 'Web photos se train, mobile photos pe test',
        why: 'Aksar achha training data aur asli use ka data alag hota hai. Galat split kiya to galat nateeje nikaaloge.',
        covers: ['Bahut saara internet data + thoda asli product data — kaise baantein (apne numbers)', 'Ek aur apna example (jaise voice product)', 'Train-dev set kya hai', 'Human / train / train-dev / dev / test errors se diagnosis', 'Avoidable bias, variance, data mismatch, dev pe overfit'] },
      { id: 'p7', slug: 'dl-fix-data-mismatch', part: 'Alag distribution ka data', title: 'Data mismatch kaise theek karein', subtitle: 'Training data ko asli jaisa banao',
        why: 'Data mismatch ka koi fixed formula nahi, par kuch practical tareeke hain jo aksar kaam karte hain.',
        covers: ['Train aur dev ke farak ko khud dekh ke samajhna', 'Training data ko dev jaisa banana ya aur jama karna', 'Artificial data synthesis: saaf awaaz + gaadi ka shor', 'Khatra: chhote se set se synthesize kiya to network usi pe overfit ho jaata hai (apna example)'] },
      { id: 'p8', slug: 'dl-transfer-multitask', part: 'Seekh ko aage badhana', title: 'Transfer learning aur multi-task learning', subtitle: 'Ek kaam ki seekh doosre mein',
        why: 'Chhote data wale projects ke liye transfer learning sabse bada shortcut hai.',
        covers: ['Pre-training aur fine-tuning', 'Sirf aakhri layer vs saari layers', 'Kab samajhdaari hai: same input, A mein bahut data, B mein kam', 'Multi-task: ek input se kai labels ek saath (apna example)', 'Loss: har label ka logistic loss jodo, missing labels chhod do', 'Multi-task kab kaam karta hai, aur ye transfer se kam common kyu'] },
      { id: 'p9', slug: 'dl-end-to-end', part: 'Seekh ko aage badhana', title: 'End-to-end deep learning', subtitle: 'Poori pipeline ki jagah ek network',
        why: 'Kabhi ek bada network sab kuch kar leta hai, kabhi chhote steps better hain. Ye faisla sahi lena bahut kaam ka hai.',
        covers: ['End-to-end kya: awaaz → text seedha', 'Apna example jahan do step wala pipeline better hai', 'Translation mein end-to-end kaam kyu karta hai', 'Data kam ho to steps mein todna kyu better', 'Fayde: data ko bolne do, kam hand-design', 'Nuksaan: bahut data chahiye, useful hand-designed hisse chhoot jaate hain', 'Asli sawaal: kya itna data hai?', 'Self-driving: kuch hisse DL, kuch nahi'] },
    ],
  },
  {
    id: 'd4', track: 'dl', page: 'dl-convolutional-networks.html', color: 'module-purple', short: 'DL · 4', number: '04',
    title: 'Convolutional Neural Networks', eyebrow: 'DL COURSE 4 • COMPUTER VISION',
    intro: 'Photos ke liye bane networks. Edge detection aur convolution se shuru, phir ResNet, Inception, MobileNet, object detection (YOLO), segmentation (U-Net), face recognition aur neural style transfer.',
    path: ['Convolution', 'CNN banao', 'Famous architectures', 'Detection', 'Faces aur art'],
    topics: [
      { id: 'c1', slug: 'dl-cv-edge-detection', part: 'Convolution ki buniyaad', title: 'Computer vision aur edge detection', subtitle: 'Photo mein pehle kinare dikhte hain',
        why: 'Convolution ka pehla kaam dikhta hai yahan — aur ye bhi ki normal network photos ke liye kyu nahi chalta.',
        covers: ['Computer vision ke kaam: classification, detection, style transfer', 'Badi photo ki problem: 1000×1000×3 = 30 lakh inputs', 'Chhoti photo pe vertical edge filter ka worked example (apne numbers)', 'Positive vs negative edge, horizontal filter', 'Sobel/Scharr jaise filters, aur filter ke numbers khud seekhna'] },
      { id: 'c2', slug: 'dl-padding-stride', part: 'Convolution ki buniyaad', title: 'Padding aur strided convolution', subtitle: 'Photo chhoti na ho, aur kadam bade ho',
        why: 'Har CNN architecture mein layer ka output size isi formula se nikalta hai.',
        covers: ['Do problems: photo sikudti hai, kinaare ka data kam use hota hai', 'Padding p, valid vs same', 'Same ke liye p = (f − 1)/2, aur f odd kyu', 'Stride s', 'Output size ⌊(n + 2p − f)/s⌋ + 1, worked', 'Cross-correlation vs convolution — naam ka chhota sa kissa'] },
      { id: 'c3', slug: 'dl-conv-volumes-layer', part: 'Convolution ki buniyaad', title: 'Volumes pe convolution aur ek conv layer', subtitle: 'RGB photo, kai filters, ek layer',
        why: 'Asli photos mein 3 channels hote hain aur layers mein darjanon filters. Yahan poori ek CNN layer ban jaati hai.',
        covers: ['RGB input pe 3D filter ka worked example (apne numbers)', 'Kai filters → output ke kai channels', 'Ek layer: bias + ReLU', 'Ek conv layer ke parameters ginna (apna example)', 'Notation: n_H, n_W, n_C, filter shapes', 'Ek simple ConvNet ka size-by-size safar, softmax tak (apne sizes)'] },
      { id: 'c4', slug: 'dl-pooling-cnn-example', part: 'Convolution ki buniyaad', title: 'Pooling, poora CNN example aur convolution kyu', subtitle: 'Sab jodke ek network',
        why: 'Pehli baar poora CNN dekhoge — layer by layer sizes aur parameters ke saath — aur samjhoge ki ye itna efficient kyu hai.',
        covers: ['Max pooling f = 2, s = 2 worked', 'Average pooling, pooling ke koi parameters nahi', 'LeNet jaisa example: conv-pool-conv-pool-FC-FC-softmax, sizes aur parameters ki table', 'Convolution kyu: parameter sharing', 'Sparse connections', 'Photo thodi khiske to bhi pehchaan (translation invariance)'] },
      { id: 'c5', slug: 'dl-classic-networks', part: 'Famous architectures', title: 'Classic networks: LeNet-5, AlexNet, VGG-16', subtitle: 'Doosron ke design padhna seekho',
        why: 'Achhe architectures padhna coding seekhne jaisa hai — doosron ka code padh ke hi achha code likhna aata hai.',
        covers: ['Case studies kyu padhein', 'LeNet-5: ~60 hazaar parameters, sizes ghat-te channels badhte', 'AlexNet: ~6 crore parameters, ReLU, bada', 'VGG-16: ~13.8 crore, har jagah 3×3 same conv + 2×2 pool, channels double'] },
      { id: 'c6', slug: 'dl-resnets', part: 'Famous architectures', title: 'ResNets', subtitle: 'Shortcut wala raasta',
        why: 'ResNet ne 100+ layer ke networks ko trainable banaya. Skip connection ka idea aaj har jagah hai, transformers mein bhi.',
        covers: ['Residual block: a[l+2] = g(z[l+2] + a[l])', 'Plain network: gehra karne pe training error badhne lagta hai', 'ResNet kyu kaam karta hai: identity seekhna aasan', 'Dimensions match: same conv, ya W_s', 'Photos pe ResNet ka dhaancha'] },
      { id: 'c7', slug: 'dl-inception', part: 'Famous architectures', title: '1×1 convolution aur Inception network', subtitle: 'Sab filter sizes ek saath',
        why: '1×1 convolution chhota dikhta hai par computation bachane ka bada hathiyaar hai. Inception isi pe khada hai.',
        covers: ['1×1 conv: channels ghatana (apne numbers)', 'Inception ka idea: 1×1, 3×3, 5×5, pool — sab karo', 'Computation cost: direct vs bottleneck, apne numbers ke saath', 'Inception module aur network, side branches', 'Naam ka filmi kissa'] },
      { id: 'c8', slug: 'dl-mobilenet-efficientnet', part: 'Famous architectures', title: 'MobileNet aur EfficientNet', subtitle: 'Phone pe chalne layak CNN',
        why: 'Har model server pe nahi chalta. Phone aur chhote devices ke liye kam computation wale designs chahiye.',
        covers: ['Kam compute ki zaroorat', 'Normal conv ka cost', 'Depthwise + pointwise conv ka cost, numbers ke saath', 'MobileNet v1', 'MobileNet v2: expansion, residual, bottleneck block', 'EfficientNet: resolution, depth, width ko saath scale'] },
      { id: 'c9', slug: 'dl-cnn-practical-advice', part: 'Famous architectures', title: 'CNN practical advice', subtitle: 'Open source, transfer learning, augmentation',
        why: 'Asli project mein zero se network kam hi banate hain. Ye page batata hai ki pro log kaise shuru karte hain.',
        covers: ['GitHub pe open-source implementation se shuru', 'Transfer learning: freeze karna, activations pehle nikaal ke rakhna, data zyada to zyada layers train', 'Augmentation: mirror, random crop, rotation, shearing, color shift', 'Augmentation training ke saath parallel', 'Computer vision ki haalat: kam data = zyada hand-engineering', 'Benchmark tricks: ensembling, test pe multi-crop'] },
      { id: 'c10', slug: 'dl-localization-landmarks', part: 'Object detection', title: 'Object localization aur landmark detection', subtitle: 'Kya hai, aur kahan hai',
        why: 'Detection ki taraf pehla kadam: sirf “gaadi hai” nahi, “gaadi yahan hai”.',
        covers: ['Classification + localization', 'Output y = [p_c, b_x, b_y, b_h, b_w, c₁, c₂, c₃]', 'Loss: p_c = 0 ho to baaki ignore', 'Landmark detection: chehre ke points, body pose', 'Labels har photo mein same order mein'] },
      { id: 'c11', slug: 'dl-sliding-windows', part: 'Object detection', title: 'Sliding windows aur uska convolutional version', subtitle: 'Khidki ghumao, par smart tarike se',
        why: 'Detection ka seedha tareeka bahut slow hai. Convolution se usko tez karne ki trick YOLO tak le jaati hai.',
        covers: ['Kasi hui (cropped) gaadi ki photos se classifier', 'Sliding window aur uska computation cost', 'FC layer ko conv layer banana', 'Ek hi pass mein saari windows — apne sizes ke saath worked', 'Kamzori: box ki jagah accurate nahi'] },
      { id: 'c12', slug: 'dl-yolo', part: 'Object detection', title: 'YOLO: IoU, non-max suppression, anchor boxes', subtitle: 'Ek nazar mein sab dhoondo',
        why: 'Real-time detection ka sabse famous algorithm. Isme detection ke saare zaroori tukde ek saath aate hain.',
        covers: ['Photo ko grid mein baantna, har cell ka output', 'Object us cell ko jisme uska center ho', 'b_x, b_y, b_h, b_w cell ke hisaab se (b_h, b_w 1 se bade ho sakte)', 'IoU worked example, 0.5 threshold', 'Non-max suppression ke steps', 'Anchor boxes: ek cell mein do objects', 'Poora YOLO: output tensor ka shape (grid × anchors × values), training aur prediction'] },
      { id: 'c13', slug: 'dl-region-proposals-unet', part: 'Object detection', title: 'Region proposals aur semantic segmentation (U-Net)', subtitle: 'Box se aage: har pixel ka label',
        why: 'Medical scans aur self-driving mein box kaafi nahi — har pixel ka pata chahiye. U-Net iska standard jawab hai.',
        covers: ['R-CNN, Fast R-CNN, Faster R-CNN ka idea', 'Semantic segmentation: har pixel ki class', 'Transpose convolution: chhota → bada, worked example', 'U-Net: pehle chhota, phir bada, skip connections kyu', 'Output: h × w × classes'] },
      { id: 'c14', slug: 'dl-face-recognition', part: 'Faces aur art', title: 'Face recognition: one-shot, Siamese, triplet loss', subtitle: 'Ek hi photo se pehchaan',
        why: 'Office ka face gate, phone unlock — sab isi idea pe. Aur ye “ek example se seekhna” ki problem ka khoobsurat hal hai.',
        covers: ['Verification (1:1) vs recognition (1:K), liveness', 'One-shot learning aur similarity function d(img1, img2) ≤ τ', 'Siamese network: photo → 128 numbers ki encoding', 'Triplet loss: anchor, positive, negative, margin α', 'Mushkil triplets chunna, training ke liye ek insaan ki kai photos', 'Verification ko binary classification banana', 'Database ki encodings pehle se nikaal ke rakhna'] },
      { id: 'c15', slug: 'dl-neural-style-transfer', part: 'Faces aur art', title: 'Neural style transfer aur ConvNet andar kya seekhta hai', subtitle: 'Tumhari photo, kisi painting ke style mein',
        why: 'Maza bhi, aur ye samajh bhi ki CNN ki alag layers photo ke alag hisse pakadti hain.',
        covers: ['Content C, style S, generated G', 'Hidden units kya dekhte hain: layer 1 kinaare, gehri layers textures aur objects', 'Cost J(G) = α J_content + β J_style, pixels pe gradient descent', 'Content cost: ek layer ke activations ka farak', 'Style cost: Gram matrix, channels ki correlation, kai layers', '1D aur 3D convolution: ECG, CT scan, video'] },
    ],
  },
  {
    id: 'd5', track: 'dl', page: 'dl-sequence-models.html', color: 'module-green', short: 'DL · 5', number: '05',
    title: 'Sequence Models', eyebrow: 'DL COURSE 5 • AWAAZ, TEXT, TRANSLATION, TRANSFORMERS',
    intro: 'Jahan order matter karta hai: sentences, awaaz, music. RNN, GRU, LSTM, word embeddings (Word2Vec, GloVe), seq2seq aur beam search, attention, speech, aur aakhir mein Transformers — aaj ke language models ki neev.',
    path: ['RNN', 'GRU/LSTM', 'Word embeddings', 'Seq2seq + attention', 'Transformers'],
    topics: [
      { id: 'q1', slug: 'dl-why-sequence-models', part: 'RNN', title: 'Sequence models kyu, aur notation', subtitle: 'Jab order matter karta hai',
        why: 'Pehle ye samajhna ki sequence wale data mein kya alag hai, aur shabdon ko computer ko kaise dikhayein.',
        covers: ['Examples: speech, music, sentiment, DNA, translation, video, naam pehchanna (NER)', 'Notation: x⟨t⟩, T_x, T_y, x⁽ⁱ⁾⟨t⟩', 'Vocabulary (jaise 10,000 shabd)', 'One-hot vector', '⟨UNK⟩ token'] },
      { id: 'q2', slug: 'dl-rnn-model', part: 'RNN', title: 'Recurrent Neural Network (RNN)', subtitle: 'Yaaddasht wala network',
        why: 'RNN pehla network hai jo pichhli baat yaad rakh ke aage chalta hai. Baaki sab sequence models iske upgrade hain.',
        covers: ['Normal network kyu nahi: alag lengths, position pe seekh share nahi', 'RNN ko time mein khol ke dekhna', 'a⟨t⟩ = g(W_aa a⟨t−1⟩ + W_ax x⟨t⟩ + b_a), ŷ⟨t⟩ = g(W_ya a⟨t⟩ + b_y)', 'Chhoti notation: W_a[a, x]', 'Activations: tanh/ReLU andar, sigmoid/softmax output', 'Kamzori: sirf pichhla context dikhta hai'] },
      { id: 'q3', slug: 'dl-bptt-rnn-types', part: 'RNN', title: 'Backprop through time aur RNN ke types', subtitle: 'Many-to-many, many-to-one, one-to-many',
        why: 'Har sequence problem ka apna shape hai. Sahi shape chuno to aadha design ho gaya.',
        covers: ['Har time step pe loss, total loss sum', 'Backprop through time ka intuition', 'Many-to-many (T_x = T_y): naam pehchanna', 'Many-to-one: sentiment', 'One-to-many: music banana', 'Many-to-many alag lengths: translation (encoder-decoder)', 'One-to-one'] },
      { id: 'q4', slug: 'dl-language-model-sampling', part: 'RNN', title: 'Language model aur naye sentences banana', subtitle: 'Agla shabd kya hoga?',
        why: 'Aaj ke chatbots isi idea ka bahut bada roop hain. Yahan uska sabse chhota version khud banana samjhoge.',
        covers: ['Language model kya karta hai: P(sentence)', 'Corpus, tokenize, ⟨EOS⟩, ⟨UNK⟩', 'RNN har step agla shabd softmax se predict kare', 'Loss: har step ka cross-entropy', 'P(y₁, y₂, y₃) = P(y₁)·P(y₂ | y₁)·P(y₃ | y₁, y₂)', 'Sampling se naye sentences banana', 'Character-level vs word-level'] },
      { id: 'q5', slug: 'dl-vanishing-gradients-gru', part: 'Lambi yaaddasht', title: 'Vanishing gradients aur GRU', subtitle: 'Lambi baat yaad rakhna',
        why: 'Normal RNN lambe sentences mein shuru ki baat bhool jaata hai. GRU usko yaad rakhne ka gate deta hai.',
        covers: ['Lambi dependency: “ladka … gaya” vs “ladki … gayi” jaisa example', 'RNN mein vanishing gradients', 'Exploding gradients aur gradient clipping', 'GRU: memory cell c⟨t⟩, candidate c̃⟨t⟩', 'Update gate Γ_u aur c⟨t⟩ = Γ_u * c̃ + (1 − Γ_u) * c⟨t−1⟩', 'Full GRU: relevance gate Γ_r', 'Gate ≈ 0 = yaad rakho'] },
      { id: 'q6', slug: 'dl-lstm-brnn-deep-rnn', part: 'Lambi yaaddasht', title: 'LSTM, bidirectional RNN aur deep RNN', subtitle: 'Teen gates, do dishaayein, kai layers',
        why: 'LSTM saalon tak sequence models ka raja raha. BRNN aur deep RNN uske saath aane wale do bade upgrade hain.',
        covers: ['LSTM ke gates: update, forget, output', 'c⟨t⟩ = Γ_u * c̃ + Γ_f * c⟨t−1⟩, a⟨t⟩ = Γ_o * tanh(c⟨t⟩)', 'Peephole connection ka zikr', 'GRU ya LSTM — kab kya', 'Bidirectional RNN: aage aur peeche dono context, poora sequence chahiye', 'Deep RNN: layers stack, aam taur pe 3 tak'] },
      { id: 'q7', slug: 'dl-word-embeddings', part: 'Word embeddings', title: 'Word embeddings: shabdon ko matlab wale numbers', subtitle: 'Aam aur santra paas-paas',
        why: 'Computer ko shabdon ke beech ka rishta samjhaane ka tareeka. Aaj ka poora NLP isi pe khada hai.',
        covers: ['One-hot ki kamzori: koi similarity nahi', 'Featurized representation: gender, royal, umar, khana…', 't-SNE se 2D mein dekhna', 'Embeddings ka use: bade text se seekho, chhote task pe transfer, chaaho to fine-tune', 'Face encoding se rishta', 'Analogies: e_man − e_woman ≈ e_king − e_queen', 'Cosine similarity'] },
      { id: 'q8', slug: 'dl-word2vec-negative-sampling', part: 'Word embeddings', title: 'Embedding matrix, Word2Vec aur negative sampling', subtitle: 'Embeddings seekhte kaise hain',
        why: 'Embeddings kahin se aasmaan se nahi girte. Yahan dekhoge ki ek simple sa prediction task unhe kaise sikha deta hai.',
        covers: ['Embedding matrix E (300 × 10,000), E·o_j = e_j (practice mein lookup)', 'Neural language model se embeddings seekhna', 'Context ke options: pichhle 4 shabd, dono taraf, paas ka ek shabd', 'Skip-gram: context → target, 10k softmax mehenga', 'Hierarchical softmax ka zikr', 'Context sample kaise: “the”, “ka” jaise shabd kam', 'Negative sampling: 1 sahi + k galat, binary classifiers', 'Negatives f(w)^{3/4} ke hisaab se'] },
      { id: 'q9', slug: 'dl-glove-sentiment-debiasing', part: 'Word embeddings', title: 'GloVe, sentiment classification aur bias hatana', subtitle: 'Embeddings ka use, aur unki zimmedari',
        why: 'Embeddings seekhne ka ek aur tareeka, unka ek asli use, aur ek zaroori sawaal: kya ye samaj ke bias bhi seekh lete hain?',
        covers: ['GloVe: co-occurrence counts X_ij aur objective', 'Embedding ki axes ka seedha matlab zaroori nahi', 'Sentiment: embeddings ka average aur “not good” wali problem', 'RNN many-to-one se better sentiment', 'Bias: direction pehchano, neutralize, equalize', 'Ye kyu zaroori hai'] },
      { id: 'q10', slug: 'dl-seq2seq-beam-search', part: 'Seq2seq aur attention', title: 'Sequence-to-sequence aur beam search', subtitle: 'Translation ka pehla tareeka',
        why: 'Translation, captions, summaries — sab seq2seq hain. Aur beam search batata hai ki ek achha output kaise chunein.',
        covers: ['Encoder-decoder se translation', 'Image captioning: CNN encoder + RNN decoder', 'Conditional language model P(y | x)', 'Greedy kyu galat — worked example', 'Beam search, B = 3, step by step', 'B = 1 = greedy'] },
      { id: 'q11', slug: 'dl-beam-refinements-bleu', part: 'Seq2seq aur attention', title: 'Beam search refinements, error analysis aur BLEU', subtitle: 'Output kitna achha, kaise naapein',
        why: 'Beam search ko practical banana, galti beam ki hai ya model ki — ye pehchanna, aur translation ko ek number mein judge karna.',
        covers: ['Probabilities ka product → logs ka sum', 'Length normalization 1/T_y^α (α ≈ 0.7)', 'B kaise chunein (1, 3, 10, 100, 1000)', 'Beam search best ki guarantee nahi deta', 'Error analysis: P(y* | x) vs P(ŷ | x) se dosh beam ka ya RNN ka', 'BLEU: kai reference translations', 'Modified precision (clipping) worked, bigrams, 1–4 grams, brevity penalty'] },
      { id: 'q12', slug: 'dl-attention-model', part: 'Seq2seq aur attention', title: 'Attention model', subtitle: 'Poora sentence ek saath yaad nahi, dhyan jahan zaroori',
        why: 'Attention ne translation ko badal diya — aur yahi idea aage Transformers ka dil bana.',
        covers: ['Lambe sentences pe seq2seq kamzor kyu (BLEU girta hai)', 'Insaani translator ki tarah tukdon mein', 'Bidirectional encoder ke features a⟨t′⟩', 'Attention weights α⟨t, t′⟩, softmax se sum 1', 'Context c⟨t⟩ = Σ α⟨t, t′⟩ a⟨t′⟩', 'Chhota network e⟨t, t′⟩ nikaale s⟨t−1⟩ aur a⟨t′⟩ se', 'Quadratic cost', 'Attention weights ki tasveer, date format example'] },
      { id: 'q13', slug: 'dl-speech-trigger-word', part: 'Seq2seq aur attention', title: 'Speech recognition aur trigger word detection', subtitle: '“Hey phone” sunna',
        why: 'Sequence models ka ek bahut asli use — awaaz. Aur CTC ka chalaak idea jo lambi awaaz ko chhote text se jodta hai.',
        covers: ['Awaaz → spectrogram', 'Phonemes wala purana tareeka vs end-to-end', 'Bade datasets (hazaaron ghante)', 'Speech ke liye attention model', 'CTC: repeat characters aur blank ko collapse karna (worked)', 'Trigger word: word ke baad label 1', 'Imbalance: 1 ko thodi der tak rakho'] },
      { id: 'q14', slug: 'dl-transformer-self-attention', part: 'Transformers', title: 'Transformer intuition aur self-attention', subtitle: 'Har shabd baaki sab shabdon ko dekhe',
        why: 'Aaj ke saare bade language models Transformers hain. Self-attention unka engine hai.',
        covers: ['RNN/LSTM sequential hain, isliye slow aur bottleneck', 'Transformer: attention + CNN jaisa parallel kaam', 'Har shabd ke liye query, key, value (W^Q, W^K, W^V)', 'A(q, K, V) = Σ softmax(q·k) v, worked example', 'Matrix form: softmax(QKᵀ / √d_k) V', '√d_k se divide kyu'] },
      { id: 'q15', slug: 'dl-multihead-transformer', part: 'Transformers', title: 'Multi-head attention aur Transformer network', subtitle: 'Poora dhaancha ek saath',
        why: 'Specialization ka aakhri tukda — aur woh architecture jo BERT, GPT jaise models ke peeche hai.',
        covers: ['Multi-head: kai alag “sawaal” ek saath, concat × W^O', 'Encoder block: multi-head attention + feed-forward, N baar', 'Decoder: masked self-attention, phir encoder-decoder attention (Q decoder se, K, V encoder se)', 'Positional encoding (sin/cos) — order ka pata kaise chale', 'Add & Norm: residual + layer norm', 'Linear + softmax output', 'Training mein masking', 'BERT, GPT kahan fit hote hain'] },
    ],
  },
];

// Pehle ye maths pages dekh lo (topic → maths topics). Maths pages pe ulta link khud banta hai.
const needs = {
  s2: ['z2', 'z3'], s3: ['z1', 'z2'], s4: ['z7'], s5: ['z6', 'z8'], s6: ['z5'], s7: ['z2'], s8: ['z4'], s9: ['z2'], s10: ['z4'], s12: ['z1'],
  a1: ['z3'], a2: ['z6'], a3: ['z8'], a4: ['z2'], a5: ['z4', 'z5'], a6: ['z7'], a10: ['z5'], a11: ['z4', 'z5'],
  u2: ['z6', 'z12'], u4: ['z5'], u5: ['z5'], u6: ['z6'], u7: ['z6'], u8: ['z5'], u9: ['z6', 'z12'], u10: ['z6'], u11: ['z4'], u12: ['z5'],
  n2: ['z6', 'z9'], n3: ['z4'], n4: ['z7', 'z10'], n5: ['z10', 'z11'], n6: ['z9'], n7: ['z6'], n8: ['z10'], n9: ['z11', 'z15'], n10: ['z11'],
  i2: ['z12'], i5: ['z5'], i6: ['z15'], i7: ['z7', 'z12'], i9: ['z13'], i10: ['z13'], i11: ['z4'], i12: ['z15'], i13: ['z5', 'z13'], i14: ['z4', 'z14'], i15: ['z8'],
  p2: ['z5'],
  c1: ['z16'], c2: ['z16'], c3: ['z16'], c4: ['z16'], c14: ['z12'], c15: ['z6'],
  q4: ['z14'], q7: ['z12'], q8: ['z4', 'z14'], q10: ['z14'], q11: ['z4'], q12: ['z4'], q14: ['z6', 'z12'],
};

const tracks = [
  { id: 'maths', page: 'maths.html', short: 'Maths', title: 'Maths — zero se deep learning tak', modules: ['m0'],
    blurb: 'Dono specializations ki shared maths. Level 1 se Level 3 tak dheere-dheere.' },
  { id: 'ml', page: 'ml.html', short: 'ML', title: 'Machine Learning Specialization', modules: ['m1', 'm2', 'm3'],
    blurb: 'Regression se reinforcement learning tak — 3 courses. Beginner ke liye pehla raasta.' },
  { id: 'dl', page: 'dl.html', short: 'DL', title: 'Deep Learning Specialization', modules: ['d1', 'd2', 'd3', 'd4', 'd5'],
    blurb: 'Neural network haath se banana, tune karna, projects chalana, CNN aur Transformers — 5 courses.' },
];

module.exports = { modules, tracks, needs };
